spring:
  security:
    oauth2:
      authorization:
        client:
          client-id: client-app
          client-secret: im-a-secret
          authorization-grant-type: authorization_code
          redirect-uri: http://localhost:8090/login/oauth2/code/client-app
            scope:
              - openid
              - profile
              - read
              - write
        provider-settings:
          issuer: http://localhost:9100  # URL completa del servidor de autenticación