spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9100  # URL completa del servidor de autenticación
      client:
        registration:
          client-app:
            provider: auth-server-custom-provider
            client-id: client-app
            client-secret: im-a-secret
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - openid
              - profile
              - read
              - write
            client-name: client-app
        provider:
          auth-server-custom-provider:
            issuer-uri: http://localhost:9100  # URL completa del servidor de autenticación