spring:
  security:
    oauth2:
      authorizationserver:
        issuer: http://auth-server:9100
        client:
          client-app:
            registration:
              client-id: "client-app"
              client-secret: "{noop}im-a-secret"
              client-name: "API Gateway solution"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://127.0.0.1:8090/login/oauth2/code/client-app"
                - "http://127.0.0.1:8090/authorized"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8090/"
              scopes:
                - "openid"
                - "profile"
                - "read"
                - "write"
            require-authorization-consent: false