spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://127.0.0.1:9100"
          key: "Im-a-secret-jwt-key"
      client:
        registration:
          client-app:
            provider: spring
            client-id: client-app
            client-secret: im-a-secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8090/authorized"
            scope:
              - openid
              - profile
              - read
              - write
            client-name: client-app
        provider:
          spring:
            issuer-uri: "http://127.0.0.1:9100"