spring:
  security:
    oauth2:
      client:
        registration:
          client-app-oidc:
            provider: spring
            client-id: client-app
            client-secret: im-a-secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8090/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: client-app-oidc
          client-app-authorization-code:
            provider: spring
            client-id: client-app
            client-secret: im-a-secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8090/authorized"
            scope: 
              - openid
              - profile
              - read
              - write
            client-name: client-app-authorization-code
        provider:
          spring:
            issuer-uri: http://auth-server:9100 # URL completa del servidor de autenticación